// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"blogg/internal/core/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthServicePort creates a new instance of MockAuthServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServicePort {
	mock := &MockAuthServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthServicePort is an autogenerated mock type for the AuthServicePort type
type MockAuthServicePort struct {
	mock.Mock
}

type MockAuthServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServicePort) EXPECT() *MockAuthServicePort_Expecter {
	return &MockAuthServicePort_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthServicePort
func (_mock *MockAuthServicePort) Login(ctx context.Context, u *domain.UserLoginReq) (*domain.UserLoginRes, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.UserLoginRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserLoginReq) (*domain.UserLoginRes, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserLoginReq) *domain.UserLoginRes); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserLoginRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.UserLoginReq) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServicePort_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServicePort_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.UserLoginReq
func (_e *MockAuthServicePort_Expecter) Login(ctx interface{}, u interface{}) *MockAuthServicePort_Login_Call {
	return &MockAuthServicePort_Login_Call{Call: _e.mock.On("Login", ctx, u)}
}

func (_c *MockAuthServicePort_Login_Call) Run(run func(ctx context.Context, u *domain.UserLoginReq)) *MockAuthServicePort_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UserLoginReq
		if args[1] != nil {
			arg1 = args[1].(*domain.UserLoginReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServicePort_Login_Call) Return(userLoginRes *domain.UserLoginRes, err error) *MockAuthServicePort_Login_Call {
	_c.Call.Return(userLoginRes, err)
	return _c
}

func (_c *MockAuthServicePort_Login_Call) RunAndReturn(run func(ctx context.Context, u *domain.UserLoginReq) (*domain.UserLoginRes, error)) *MockAuthServicePort_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthServicePort
func (_mock *MockAuthServicePort) Register(ctx context.Context, u *domain.UserRegisterReq) (*domain.UserRegisterRes, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.UserRegisterRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserRegisterReq) (*domain.UserRegisterRes, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserRegisterReq) *domain.UserRegisterRes); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRegisterRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.UserRegisterReq) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServicePort_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServicePort_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.UserRegisterReq
func (_e *MockAuthServicePort_Expecter) Register(ctx interface{}, u interface{}) *MockAuthServicePort_Register_Call {
	return &MockAuthServicePort_Register_Call{Call: _e.mock.On("Register", ctx, u)}
}

func (_c *MockAuthServicePort_Register_Call) Run(run func(ctx context.Context, u *domain.UserRegisterReq)) *MockAuthServicePort_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UserRegisterReq
		if args[1] != nil {
			arg1 = args[1].(*domain.UserRegisterReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServicePort_Register_Call) Return(userRegisterRes *domain.UserRegisterRes, err error) *MockAuthServicePort_Register_Call {
	_c.Call.Return(userRegisterRes, err)
	return _c
}

func (_c *MockAuthServicePort_Register_Call) RunAndReturn(run func(ctx context.Context, u *domain.UserRegisterReq) (*domain.UserRegisterRes, error)) *MockAuthServicePort_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepositoryPort creates a new instance of MockAuthRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepositoryPort {
	mock := &MockAuthRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepositoryPort is an autogenerated mock type for the AuthRepositoryPort type
type MockAuthRepositoryPort struct {
	mock.Mock
}

type MockAuthRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepositoryPort) EXPECT() *MockAuthRepositoryPort_Expecter {
	return &MockAuthRepositoryPort_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) CreateUser(ctx context.Context, u *domain.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepositoryPort_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepositoryPort_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockAuthRepositoryPort_Expecter) CreateUser(ctx interface{}, u interface{}) *MockAuthRepositoryPort_CreateUser_Call {
	return &MockAuthRepositoryPort_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, u)}
}

func (_c *MockAuthRepositoryPort_CreateUser_Call) Run(run func(ctx context.Context, u *domain.User)) *MockAuthRepositoryPort_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_CreateUser_Call) Return(err error) *MockAuthRepositoryPort_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepositoryPort_CreateUser_Call) RunAndReturn(run func(ctx context.Context, u *domain.User) error) *MockAuthRepositoryPort_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) FindUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepositoryPort_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockAuthRepositoryPort_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepositoryPort_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockAuthRepositoryPort_FindUserByEmail_Call {
	return &MockAuthRepositoryPort_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockAuthRepositoryPort_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepositoryPort_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByEmail_Call) Return(user *domain.User, err error) *MockAuthRepositoryPort_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockAuthRepositoryPort_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) FindUserByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepositoryPort_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockAuthRepositoryPort_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthRepositoryPort_Expecter) FindUserByID(ctx interface{}, userID interface{}) *MockAuthRepositoryPort_FindUserByID_Call {
	return &MockAuthRepositoryPort_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, userID)}
}

func (_c *MockAuthRepositoryPort_FindUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockAuthRepositoryPort_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByID_Call) Return(user *domain.User, err error) *MockAuthRepositoryPort_FindUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.User, error)) *MockAuthRepositoryPort_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) FindUserByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepositoryPort_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockAuthRepositoryPort_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockAuthRepositoryPort_Expecter) FindUserByUsername(ctx interface{}, username interface{}) *MockAuthRepositoryPort_FindUserByUsername_Call {
	return &MockAuthRepositoryPort_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *MockAuthRepositoryPort_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockAuthRepositoryPort_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByUsername_Call) Return(user *domain.User, err error) *MockAuthRepositoryPort_FindUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockAuthRepositoryPort_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostServicePort creates a new instance of MockPostServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostServicePort {
	mock := &MockPostServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostServicePort is an autogenerated mock type for the PostServicePort type
type MockPostServicePort struct {
	mock.Mock
}

type MockPostServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostServicePort) EXPECT() *MockPostServicePort_Expecter {
	return &MockPostServicePort_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function for the type MockPostServicePort
func (_mock *MockPostServicePort) CreatePost(ctx context.Context, req *domain.Post, categoryIDs []string) (*domain.Post, error) {
	ret := _mock.Called(ctx, req, categoryIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post, []string) (*domain.Post, error)); ok {
		return returnFunc(ctx, req, categoryIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post, []string) *domain.Post); ok {
		r0 = returnFunc(ctx, req, categoryIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Post, []string) error); ok {
		r1 = returnFunc(ctx, req, categoryIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostServicePort_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockPostServicePort_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.Post
//   - categoryIDs []string
func (_e *MockPostServicePort_Expecter) CreatePost(ctx interface{}, req interface{}, categoryIDs interface{}) *MockPostServicePort_CreatePost_Call {
	return &MockPostServicePort_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, req, categoryIDs)}
}

func (_c *MockPostServicePort_CreatePost_Call) Run(run func(ctx context.Context, req *domain.Post, categoryIDs []string)) *MockPostServicePort_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Post
		if args[1] != nil {
			arg1 = args[1].(*domain.Post)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostServicePort_CreatePost_Call) Return(post *domain.Post, err error) *MockPostServicePort_CreatePost_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostServicePort_CreatePost_Call) RunAndReturn(run func(ctx context.Context, req *domain.Post, categoryIDs []string) (*domain.Post, error)) *MockPostServicePort_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePost provides a mock function for the type MockPostServicePort
func (_mock *MockPostServicePort) DeletePost(ctx context.Context, id string, userID string) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostServicePort_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockPostServicePort_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
func (_e *MockPostServicePort_Expecter) DeletePost(ctx interface{}, id interface{}, userID interface{}) *MockPostServicePort_DeletePost_Call {
	return &MockPostServicePort_DeletePost_Call{Call: _e.mock.On("DeletePost", ctx, id, userID)}
}

func (_c *MockPostServicePort_DeletePost_Call) Run(run func(ctx context.Context, id string, userID string)) *MockPostServicePort_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostServicePort_DeletePost_Call) Return(err error) *MockPostServicePort_DeletePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostServicePort_DeletePost_Call) RunAndReturn(run func(ctx context.Context, id string, userID string) error) *MockPostServicePort_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPost provides a mock function for the type MockPostServicePort
func (_mock *MockPostServicePort) GetPost(ctx context.Context, id string) (*domain.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPost")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostServicePort_GetPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPost'
type MockPostServicePort_GetPost_Call struct {
	*mock.Call
}

// GetPost is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPostServicePort_Expecter) GetPost(ctx interface{}, id interface{}) *MockPostServicePort_GetPost_Call {
	return &MockPostServicePort_GetPost_Call{Call: _e.mock.On("GetPost", ctx, id)}
}

func (_c *MockPostServicePort_GetPost_Call) Run(run func(ctx context.Context, id string)) *MockPostServicePort_GetPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostServicePort_GetPost_Call) Return(post *domain.Post, err error) *MockPostServicePort_GetPost_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostServicePort_GetPost_Call) RunAndReturn(run func(ctx context.Context, id string) (*domain.Post, error)) *MockPostServicePort_GetPost_Call {
	_c.Call.Return(run)
	return _c
}

// ListPosts provides a mock function for the type MockPostServicePort
func (_mock *MockPostServicePort) ListPosts(ctx context.Context) ([]*domain.Post, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPosts")
	}

	var r0 []*domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Post, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Post); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostServicePort_ListPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPosts'
type MockPostServicePort_ListPosts_Call struct {
	*mock.Call
}

// ListPosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPostServicePort_Expecter) ListPosts(ctx interface{}) *MockPostServicePort_ListPosts_Call {
	return &MockPostServicePort_ListPosts_Call{Call: _e.mock.On("ListPosts", ctx)}
}

func (_c *MockPostServicePort_ListPosts_Call) Run(run func(ctx context.Context)) *MockPostServicePort_ListPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPostServicePort_ListPosts_Call) Return(posts []*domain.Post, err error) *MockPostServicePort_ListPosts_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockPostServicePort_ListPosts_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Post, error)) *MockPostServicePort_ListPosts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePost provides a mock function for the type MockPostServicePort
func (_mock *MockPostServicePort) UpdatePost(ctx context.Context, id string, userID string, req *domain.Post, categoryIDs *[]string) (*domain.Post, error) {
	ret := _mock.Called(ctx, id, userID, req, categoryIDs)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Post, *[]string) (*domain.Post, error)); ok {
		return returnFunc(ctx, id, userID, req, categoryIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *domain.Post, *[]string) *domain.Post); ok {
		r0 = returnFunc(ctx, id, userID, req, categoryIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *domain.Post, *[]string) error); ok {
		r1 = returnFunc(ctx, id, userID, req, categoryIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostServicePort_UpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePost'
type MockPostServicePort_UpdatePost_Call struct {
	*mock.Call
}

// UpdatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - userID string
//   - req *domain.Post
//   - categoryIDs *[]string
func (_e *MockPostServicePort_Expecter) UpdatePost(ctx interface{}, id interface{}, userID interface{}, req interface{}, categoryIDs interface{}) *MockPostServicePort_UpdatePost_Call {
	return &MockPostServicePort_UpdatePost_Call{Call: _e.mock.On("UpdatePost", ctx, id, userID, req, categoryIDs)}
}

func (_c *MockPostServicePort_UpdatePost_Call) Run(run func(ctx context.Context, id string, userID string, req *domain.Post, categoryIDs *[]string)) *MockPostServicePort_UpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *domain.Post
		if args[3] != nil {
			arg3 = args[3].(*domain.Post)
		}
		var arg4 *[]string
		if args[4] != nil {
			arg4 = args[4].(*[]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockPostServicePort_UpdatePost_Call) Return(post *domain.Post, err error) *MockPostServicePort_UpdatePost_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostServicePort_UpdatePost_Call) RunAndReturn(run func(ctx context.Context, id string, userID string, req *domain.Post, categoryIDs *[]string) (*domain.Post, error)) *MockPostServicePort_UpdatePost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostRepositoryPort creates a new instance of MockPostRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepositoryPort {
	mock := &MockPostRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostRepositoryPort is an autogenerated mock type for the PostRepositoryPort type
type MockPostRepositoryPort struct {
	mock.Mock
}

type MockPostRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepositoryPort) EXPECT() *MockPostRepositoryPort_Expecter {
	return &MockPostRepositoryPort_Expecter{mock: &_m.Mock}
}

// AddCategoriesToPost provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) AddCategoriesToPost(ctx context.Context, postID string, categoryIDs []string) error {
	ret := _mock.Called(ctx, postID, categoryIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddCategoriesToPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = returnFunc(ctx, postID, categoryIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryPort_AddCategoriesToPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCategoriesToPost'
type MockPostRepositoryPort_AddCategoriesToPost_Call struct {
	*mock.Call
}

// AddCategoriesToPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
//   - categoryIDs []string
func (_e *MockPostRepositoryPort_Expecter) AddCategoriesToPost(ctx interface{}, postID interface{}, categoryIDs interface{}) *MockPostRepositoryPort_AddCategoriesToPost_Call {
	return &MockPostRepositoryPort_AddCategoriesToPost_Call{Call: _e.mock.On("AddCategoriesToPost", ctx, postID, categoryIDs)}
}

func (_c *MockPostRepositoryPort_AddCategoriesToPost_Call) Run(run func(ctx context.Context, postID string, categoryIDs []string)) *MockPostRepositoryPort_AddCategoriesToPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_AddCategoriesToPost_Call) Return(err error) *MockPostRepositoryPort_AddCategoriesToPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryPort_AddCategoriesToPost_Call) RunAndReturn(run func(ctx context.Context, postID string, categoryIDs []string) error) *MockPostRepositoryPort_AddCategoriesToPost_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePost provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) CreatePost(ctx context.Context, p *domain.Post) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryPort_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockPostRepositoryPort_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Post
func (_e *MockPostRepositoryPort_Expecter) CreatePost(ctx interface{}, p interface{}) *MockPostRepositoryPort_CreatePost_Call {
	return &MockPostRepositoryPort_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, p)}
}

func (_c *MockPostRepositoryPort_CreatePost_Call) Run(run func(ctx context.Context, p *domain.Post)) *MockPostRepositoryPort_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Post
		if args[1] != nil {
			arg1 = args[1].(*domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_CreatePost_Call) Return(err error) *MockPostRepositoryPort_CreatePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryPort_CreatePost_Call) RunAndReturn(run func(ctx context.Context, p *domain.Post) error) *MockPostRepositoryPort_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePost provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) DeletePost(ctx context.Context, postID string) error {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryPort_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockPostRepositoryPort_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockPostRepositoryPort_Expecter) DeletePost(ctx interface{}, postID interface{}) *MockPostRepositoryPort_DeletePost_Call {
	return &MockPostRepositoryPort_DeletePost_Call{Call: _e.mock.On("DeletePost", ctx, postID)}
}

func (_c *MockPostRepositoryPort_DeletePost_Call) Run(run func(ctx context.Context, postID string)) *MockPostRepositoryPort_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_DeletePost_Call) Return(err error) *MockPostRepositoryPort_DeletePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryPort_DeletePost_Call) RunAndReturn(run func(ctx context.Context, postID string) error) *MockPostRepositoryPort_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// FindPostByID provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) FindPostByID(ctx context.Context, postID string) (*domain.Post, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for FindPostByID")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepositoryPort_FindPostByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPostByID'
type MockPostRepositoryPort_FindPostByID_Call struct {
	*mock.Call
}

// FindPostByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockPostRepositoryPort_Expecter) FindPostByID(ctx interface{}, postID interface{}) *MockPostRepositoryPort_FindPostByID_Call {
	return &MockPostRepositoryPort_FindPostByID_Call{Call: _e.mock.On("FindPostByID", ctx, postID)}
}

func (_c *MockPostRepositoryPort_FindPostByID_Call) Run(run func(ctx context.Context, postID string)) *MockPostRepositoryPort_FindPostByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_FindPostByID_Call) Return(post *domain.Post, err error) *MockPostRepositoryPort_FindPostByID_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostRepositoryPort_FindPostByID_Call) RunAndReturn(run func(ctx context.Context, postID string) (*domain.Post, error)) *MockPostRepositoryPort_FindPostByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPostBySlug provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) FindPostBySlug(ctx context.Context, slug string) (*domain.Post, error) {
	ret := _mock.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for FindPostBySlug")
	}

	var r0 *domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Post, error)); ok {
		return returnFunc(ctx, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Post); ok {
		r0 = returnFunc(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepositoryPort_FindPostBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPostBySlug'
type MockPostRepositoryPort_FindPostBySlug_Call struct {
	*mock.Call
}

// FindPostBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockPostRepositoryPort_Expecter) FindPostBySlug(ctx interface{}, slug interface{}) *MockPostRepositoryPort_FindPostBySlug_Call {
	return &MockPostRepositoryPort_FindPostBySlug_Call{Call: _e.mock.On("FindPostBySlug", ctx, slug)}
}

func (_c *MockPostRepositoryPort_FindPostBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockPostRepositoryPort_FindPostBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_FindPostBySlug_Call) Return(post *domain.Post, err error) *MockPostRepositoryPort_FindPostBySlug_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostRepositoryPort_FindPostBySlug_Call) RunAndReturn(run func(ctx context.Context, slug string) (*domain.Post, error)) *MockPostRepositoryPort_FindPostBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostCategories provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) GetPostCategories(ctx context.Context, postID string) ([]domain.Category, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostCategories")
	}

	var r0 []domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Category, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Category); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepositoryPort_GetPostCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostCategories'
type MockPostRepositoryPort_GetPostCategories_Call struct {
	*mock.Call
}

// GetPostCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockPostRepositoryPort_Expecter) GetPostCategories(ctx interface{}, postID interface{}) *MockPostRepositoryPort_GetPostCategories_Call {
	return &MockPostRepositoryPort_GetPostCategories_Call{Call: _e.mock.On("GetPostCategories", ctx, postID)}
}

func (_c *MockPostRepositoryPort_GetPostCategories_Call) Run(run func(ctx context.Context, postID string)) *MockPostRepositoryPort_GetPostCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_GetPostCategories_Call) Return(categorys []domain.Category, err error) *MockPostRepositoryPort_GetPostCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockPostRepositoryPort_GetPostCategories_Call) RunAndReturn(run func(ctx context.Context, postID string) ([]domain.Category, error)) *MockPostRepositoryPort_GetPostCategories_Call {
	_c.Call.Return(run)
	return _c
}

// ListPosts provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) ListPosts(ctx context.Context) ([]*domain.Post, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPosts")
	}

	var r0 []*domain.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Post, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Post); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepositoryPort_ListPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPosts'
type MockPostRepositoryPort_ListPosts_Call struct {
	*mock.Call
}

// ListPosts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPostRepositoryPort_Expecter) ListPosts(ctx interface{}) *MockPostRepositoryPort_ListPosts_Call {
	return &MockPostRepositoryPort_ListPosts_Call{Call: _e.mock.On("ListPosts", ctx)}
}

func (_c *MockPostRepositoryPort_ListPosts_Call) Run(run func(ctx context.Context)) *MockPostRepositoryPort_ListPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_ListPosts_Call) Return(posts []*domain.Post, err error) *MockPostRepositoryPort_ListPosts_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockPostRepositoryPort_ListPosts_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Post, error)) *MockPostRepositoryPort_ListPosts_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveCategoriesFromPost provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) RemoveCategoriesFromPost(ctx context.Context, postID string) error {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCategoriesFromPost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryPort_RemoveCategoriesFromPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveCategoriesFromPost'
type MockPostRepositoryPort_RemoveCategoriesFromPost_Call struct {
	*mock.Call
}

// RemoveCategoriesFromPost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID string
func (_e *MockPostRepositoryPort_Expecter) RemoveCategoriesFromPost(ctx interface{}, postID interface{}) *MockPostRepositoryPort_RemoveCategoriesFromPost_Call {
	return &MockPostRepositoryPort_RemoveCategoriesFromPost_Call{Call: _e.mock.On("RemoveCategoriesFromPost", ctx, postID)}
}

func (_c *MockPostRepositoryPort_RemoveCategoriesFromPost_Call) Run(run func(ctx context.Context, postID string)) *MockPostRepositoryPort_RemoveCategoriesFromPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_RemoveCategoriesFromPost_Call) Return(err error) *MockPostRepositoryPort_RemoveCategoriesFromPost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryPort_RemoveCategoriesFromPost_Call) RunAndReturn(run func(ctx context.Context, postID string) error) *MockPostRepositoryPort_RemoveCategoriesFromPost_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePost provides a mock function for the type MockPostRepositoryPort
func (_mock *MockPostRepositoryPort) UpdatePost(ctx context.Context, p *domain.Post) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Post) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryPort_UpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePost'
type MockPostRepositoryPort_UpdatePost_Call struct {
	*mock.Call
}

// UpdatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Post
func (_e *MockPostRepositoryPort_Expecter) UpdatePost(ctx interface{}, p interface{}) *MockPostRepositoryPort_UpdatePost_Call {
	return &MockPostRepositoryPort_UpdatePost_Call{Call: _e.mock.On("UpdatePost", ctx, p)}
}

func (_c *MockPostRepositoryPort_UpdatePost_Call) Run(run func(ctx context.Context, p *domain.Post)) *MockPostRepositoryPort_UpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Post
		if args[1] != nil {
			arg1 = args[1].(*domain.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryPort_UpdatePost_Call) Return(err error) *MockPostRepositoryPort_UpdatePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryPort_UpdatePost_Call) RunAndReturn(run func(ctx context.Context, p *domain.Post) error) *MockPostRepositoryPort_UpdatePost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepositoryPort creates a new instance of MockCategoryRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepositoryPort {
	mock := &MockCategoryRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryRepositoryPort is an autogenerated mock type for the CategoryRepositoryPort type
type MockCategoryRepositoryPort struct {
	mock.Mock
}

type MockCategoryRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepositoryPort) EXPECT() *MockCategoryRepositoryPort_Expecter {
	return &MockCategoryRepositoryPort_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function for the type MockCategoryRepositoryPort
func (_mock *MockCategoryRepositoryPort) CreateCategory(ctx context.Context, c *domain.Category) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Category) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryRepositoryPort_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryRepositoryPort_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - c *domain.Category
func (_e *MockCategoryRepositoryPort_Expecter) CreateCategory(ctx interface{}, c interface{}) *MockCategoryRepositoryPort_CreateCategory_Call {
	return &MockCategoryRepositoryPort_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, c)}
}

func (_c *MockCategoryRepositoryPort_CreateCategory_Call) Run(run func(ctx context.Context, c *domain.Category)) *MockCategoryRepositoryPort_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Category
		if args[1] != nil {
			arg1 = args[1].(*domain.Category)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepositoryPort_CreateCategory_Call) Return(err error) *MockCategoryRepositoryPort_CreateCategory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryRepositoryPort_CreateCategory_Call) RunAndReturn(run func(ctx context.Context, c *domain.Category) error) *MockCategoryRepositoryPort_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// FindCategoryByID provides a mock function for the type MockCategoryRepositoryPort
func (_mock *MockCategoryRepositoryPort) FindCategoryByID(ctx context.Context, categoryID string) (*domain.Category, error) {
	ret := _mock.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for FindCategoryByID")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Category, error)); ok {
		return returnFunc(ctx, categoryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Category); ok {
		r0 = returnFunc(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepositoryPort_FindCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindCategoryByID'
type MockCategoryRepositoryPort_FindCategoryByID_Call struct {
	*mock.Call
}

// FindCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID string
func (_e *MockCategoryRepositoryPort_Expecter) FindCategoryByID(ctx interface{}, categoryID interface{}) *MockCategoryRepositoryPort_FindCategoryByID_Call {
	return &MockCategoryRepositoryPort_FindCategoryByID_Call{Call: _e.mock.On("FindCategoryByID", ctx, categoryID)}
}

func (_c *MockCategoryRepositoryPort_FindCategoryByID_Call) Run(run func(ctx context.Context, categoryID string)) *MockCategoryRepositoryPort_FindCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCategoryRepositoryPort_FindCategoryByID_Call) Return(category *domain.Category, err error) *MockCategoryRepositoryPort_FindCategoryByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryRepositoryPort_FindCategoryByID_Call) RunAndReturn(run func(ctx context.Context, categoryID string) (*domain.Category, error)) *MockCategoryRepositoryPort_FindCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListCategories provides a mock function for the type MockCategoryRepositoryPort
func (_mock *MockCategoryRepositoryPort) ListCategories(ctx context.Context) ([]domain.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListCategories")
	}

	var r0 []domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryRepositoryPort_ListCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCategories'
type MockCategoryRepositoryPort_ListCategories_Call struct {
	*mock.Call
}

// ListCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryRepositoryPort_Expecter) ListCategories(ctx interface{}) *MockCategoryRepositoryPort_ListCategories_Call {
	return &MockCategoryRepositoryPort_ListCategories_Call{Call: _e.mock.On("ListCategories", ctx)}
}

func (_c *MockCategoryRepositoryPort_ListCategories_Call) Run(run func(ctx context.Context)) *MockCategoryRepositoryPort_ListCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCategoryRepositoryPort_ListCategories_Call) Return(categorys []domain.Category, err error) *MockCategoryRepositoryPort_ListCategories_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockCategoryRepositoryPort_ListCategories_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Category, error)) *MockCategoryRepositoryPort_ListCategories_Call {
	_c.Call.Return(run)
	return _c
}
