// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"blogg/internal/core/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthServicePort creates a new instance of MockAuthServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServicePort {
	mock := &MockAuthServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthServicePort is an autogenerated mock type for the AuthServicePort type
type MockAuthServicePort struct {
	mock.Mock
}

type MockAuthServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServicePort) EXPECT() *MockAuthServicePort_Expecter {
	return &MockAuthServicePort_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthServicePort
func (_mock *MockAuthServicePort) Login(ctx context.Context, u *domain.UserLoginReq) (*domain.UserLoginRes, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.UserLoginRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserLoginReq) (*domain.UserLoginRes, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserLoginReq) *domain.UserLoginRes); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserLoginRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.UserLoginReq) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServicePort_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServicePort_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.UserLoginReq
func (_e *MockAuthServicePort_Expecter) Login(ctx interface{}, u interface{}) *MockAuthServicePort_Login_Call {
	return &MockAuthServicePort_Login_Call{Call: _e.mock.On("Login", ctx, u)}
}

func (_c *MockAuthServicePort_Login_Call) Run(run func(ctx context.Context, u *domain.UserLoginReq)) *MockAuthServicePort_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UserLoginReq
		if args[1] != nil {
			arg1 = args[1].(*domain.UserLoginReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServicePort_Login_Call) Return(userLoginRes *domain.UserLoginRes, err error) *MockAuthServicePort_Login_Call {
	_c.Call.Return(userLoginRes, err)
	return _c
}

func (_c *MockAuthServicePort_Login_Call) RunAndReturn(run func(ctx context.Context, u *domain.UserLoginReq) (*domain.UserLoginRes, error)) *MockAuthServicePort_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthServicePort
func (_mock *MockAuthServicePort) Register(ctx context.Context, u *domain.UserRegisterReq) (*domain.UserRegisterRes, error) {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.UserRegisterRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserRegisterReq) (*domain.UserRegisterRes, error)); ok {
		return returnFunc(ctx, u)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UserRegisterReq) *domain.UserRegisterRes); ok {
		r0 = returnFunc(ctx, u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRegisterRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.UserRegisterReq) error); ok {
		r1 = returnFunc(ctx, u)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthServicePort_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServicePort_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.UserRegisterReq
func (_e *MockAuthServicePort_Expecter) Register(ctx interface{}, u interface{}) *MockAuthServicePort_Register_Call {
	return &MockAuthServicePort_Register_Call{Call: _e.mock.On("Register", ctx, u)}
}

func (_c *MockAuthServicePort_Register_Call) Run(run func(ctx context.Context, u *domain.UserRegisterReq)) *MockAuthServicePort_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UserRegisterReq
		if args[1] != nil {
			arg1 = args[1].(*domain.UserRegisterReq)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthServicePort_Register_Call) Return(userRegisterRes *domain.UserRegisterRes, err error) *MockAuthServicePort_Register_Call {
	_c.Call.Return(userRegisterRes, err)
	return _c
}

func (_c *MockAuthServicePort_Register_Call) RunAndReturn(run func(ctx context.Context, u *domain.UserRegisterReq) (*domain.UserRegisterRes, error)) *MockAuthServicePort_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepositoryPort creates a new instance of MockAuthRepositoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepositoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepositoryPort {
	mock := &MockAuthRepositoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepositoryPort is an autogenerated mock type for the AuthRepositoryPort type
type MockAuthRepositoryPort struct {
	mock.Mock
}

type MockAuthRepositoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepositoryPort) EXPECT() *MockAuthRepositoryPort_Expecter {
	return &MockAuthRepositoryPort_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) CreateUser(ctx context.Context, u *domain.User) error {
	ret := _mock.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = returnFunc(ctx, u)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthRepositoryPort_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepositoryPort_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - u *domain.User
func (_e *MockAuthRepositoryPort_Expecter) CreateUser(ctx interface{}, u interface{}) *MockAuthRepositoryPort_CreateUser_Call {
	return &MockAuthRepositoryPort_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, u)}
}

func (_c *MockAuthRepositoryPort_CreateUser_Call) Run(run func(ctx context.Context, u *domain.User)) *MockAuthRepositoryPort_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_CreateUser_Call) Return(err error) *MockAuthRepositoryPort_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthRepositoryPort_CreateUser_Call) RunAndReturn(run func(ctx context.Context, u *domain.User) error) *MockAuthRepositoryPort_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByEmail provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) FindUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepositoryPort_FindUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByEmail'
type MockAuthRepositoryPort_FindUserByEmail_Call struct {
	*mock.Call
}

// FindUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepositoryPort_Expecter) FindUserByEmail(ctx interface{}, email interface{}) *MockAuthRepositoryPort_FindUserByEmail_Call {
	return &MockAuthRepositoryPort_FindUserByEmail_Call{Call: _e.mock.On("FindUserByEmail", ctx, email)}
}

func (_c *MockAuthRepositoryPort_FindUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepositoryPort_FindUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByEmail_Call) Return(user *domain.User, err error) *MockAuthRepositoryPort_FindUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockAuthRepositoryPort_FindUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByID provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) FindUserByID(ctx context.Context, userID string) (*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepositoryPort_FindUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByID'
type MockAuthRepositoryPort_FindUserByID_Call struct {
	*mock.Call
}

// FindUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthRepositoryPort_Expecter) FindUserByID(ctx interface{}, userID interface{}) *MockAuthRepositoryPort_FindUserByID_Call {
	return &MockAuthRepositoryPort_FindUserByID_Call{Call: _e.mock.On("FindUserByID", ctx, userID)}
}

func (_c *MockAuthRepositoryPort_FindUserByID_Call) Run(run func(ctx context.Context, userID string)) *MockAuthRepositoryPort_FindUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByID_Call) Return(user *domain.User, err error) *MockAuthRepositoryPort_FindUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByID_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.User, error)) *MockAuthRepositoryPort_FindUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindUserByUsername provides a mock function for the type MockAuthRepositoryPort
func (_mock *MockAuthRepositoryPort) FindUserByUsername(ctx context.Context, username string) (*domain.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByUsername")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepositoryPort_FindUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUserByUsername'
type MockAuthRepositoryPort_FindUserByUsername_Call struct {
	*mock.Call
}

// FindUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockAuthRepositoryPort_Expecter) FindUserByUsername(ctx interface{}, username interface{}) *MockAuthRepositoryPort_FindUserByUsername_Call {
	return &MockAuthRepositoryPort_FindUserByUsername_Call{Call: _e.mock.On("FindUserByUsername", ctx, username)}
}

func (_c *MockAuthRepositoryPort_FindUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockAuthRepositoryPort_FindUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByUsername_Call) Return(user *domain.User, err error) *MockAuthRepositoryPort_FindUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepositoryPort_FindUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*domain.User, error)) *MockAuthRepositoryPort_FindUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}
